some fixes
Weab-chan/freedreno_turnip-CI pull request #2
Opened 2024-03-03 04:48 UTC by Ishan09811

2024-03-03 06:02 UTC, Weab-chan requested changes

2024-03-03 06:02 UTC, Weab-chan commented on turnip_builder.sh
> +  "name": "Mesa Turnip - $date - $commit_short",
I think adding mesa here is not necessary... is there other turnip driver maker out there?

2024-03-03 06:02 UTC, Weab-chan commented on turnip_builder.sh
> +  "description": "Vulkan $vulkan_version",
I do agree the description could describe the driver a bit more

2024-03-03 06:02 UTC, Weab-chan commented on turnip_builder.sh
> +  "driverVersion": "$mesa_version",
Following kimchi's lead, I think having the vulkan version here make sense..

2024-03-03 06:04 UTC, Weab-chan commented
Would be great to provide a rational for those change :)

2024-03-03 07:37 UTC, Ishan09811 commented
@Weab-chan 


no, kimchi is wrong because this place is for the mesa version not for the Vulkan version and you can see this when I use the driver version for the Vulkan version
![Screenshot_20240303-130607](https://github.com/Weab-chan/freedreno_turnip-CI/assets/156402647/82144641-d378-49db-aa4d-d86de571e7e5)

2024-03-03 07:52 UTC, Weab-chan commented
> @Weab-chan
> 
> no, kimchi is wrong because this place is for the mesa version not for the Vulkan version and you can see this when I use the driver version for the Vulkan version ![Screenshot_20240303-130607](https://private-user-images.githubusercontent.com/156402647/309534033-82144641-d378-49db-aa4d-d86de571e7e5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTI0NTAsIm5iZiI6MTcwOTQ1MjE1MCwicGF0aCI6Ii8xNTY0MDI2NDcvMzA5NTM0MDMzLTgyMTQ0NjQxLWQzNzgtNDlkYi1hYTRkLWQ4NmRlNTcxZTdlNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QwNzQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmM1YjkxOGYwMGZlOTBjMjY4MTIzMDNhMmNlY2UyYWEzZmRhY2U1NjM3YTNkOTVmZjVlOTRiZTg4NDZmNjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s5DwPGRK9xy8B2e3Emjhbi-IeyPX7Lw3v_cQza2od-U)

you do understand kimchi was in direct communication with the people contributing to turnip? I'm sure he was advised to do it this way too.. and your picture proves nothing

2024-03-03 08:11 UTC, Ishan09811 commented
@Weab-chan 
you didn't see the vVulkan 1.3.278 which is very weird?

2024-03-03 08:28 UTC, Weab-chan commented
> @Weab-chan you didn't see the vVulkan 1.3.278 which is very weird?

Right that's a screenshot from skyline, you should add more context lol I'll change it to be just a number i guess, good catch!

2024-03-03 08:39 UTC, Ishan09811 commented
@Weab-chan 
you can use the driver version as mesa version and discription as the Vulkan version so it will be good

2024-03-03 08:49 UTC, Weab-chan commented
Lets double check all emulators and make sure they look good

2024-03-04 10:21 UTC, Weab-chan commented
Closed due to the latest changes

2024-03-04 10:21 UTC, closed without merging